# Exported from Render on 2026-07-03T08:21:04Z
version: "1"
services:
- type: web
  name: cet_register
  runtime: docker
  repo: https://github.com/DagonRanchi/diplom
  plan: free
  envVars:
  - key: ENVIRONMENT
    sync: false
  - key: CORS_ORIGINS
    sync: false
  - key: ACCESS_TOKEN_EXPIRE_MINUTES
    sync: false
  - key: JWT_ALGORITHM
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
  rootDir: abiturients_server/backend
